name: 'bi_dev_tarea'
version: '1.0'
config-version: 2
vars:
  date_padding_days: 90   # control del rango extra de dias para dim_date

profile: 'default'  # dbt Cloud maneja esto automáticamente

model-paths: ['models']
macro-paths: ['macros']
snapshot-paths: ['snapshots']
test-paths: ['tests']
seed-paths: ['seeds']

models:
  bi_dev_tarea:
    +materialized: view  # Los modelos por defecto serán vistas
    staging:
      +schema: staging
    marts:
      +schema: marts
