name: 'bi_dev_tarea'
version: '1.0'
config-version: 2

# Variables del proyecto
vars:
  date_padding_days: 90   # control del rango extra de días para dim_date

profile: 'default'  # dbt Cloud maneja esto automáticamente

model-paths: ['models']
macro-paths: ['macros']
snapshot-paths: ['snapshots']
test-paths: ['tests']
seed-paths: ['seeds']

models:
  bi_dev_tarea:
    +materialized: view  # por defecto vistas, puedes overridear por modelo
    staging:
      +schema: staging   # resultará en <target.schema>_staging (p.ej. dbt_mbonilla_staging)
    marts:
      +schema: marts     # resultará en <target.schema>_marts (p.ej. dbt_mbonilla_marts)
